---
title: "Homework 3"
output: html_notebook
---

The dataset used is the Gender Statistics database, a comprehensive source for the latest sex-disaggregated data and gender statistics covering demography, education, health, access to economic opportunities, public life and decision-making, and agency, available at https://datacatalog.worldbank.org/dataset/gender-statistics:
```{r}
library(tidyverse)
library(ggpubr)
library(reshape2)
library(party)
library(dplyr)
library(plyr)
```

```{r}
dataset <- read.csv("Gender_StatsData.csv", stringsAsFactors=FALSE)
summary(dataset)
```

```{r}
countries <- unique(dataset[,1])
head(countries)
```
```{r}
columns = unique(dataset[,4])
head(columns)
```


```{r}
new_dat <- data.frame(row.names = countries)
for (col_name in columns) {
  col = subset(x = dataset, subset = Indicator.Code == col_name, select=X2017)
  new_dat[col_name] <- col[, "X2017"]
}
new_dat <- tail(new_dat[!sapply(new_dat, function (x) all(is.na(x) | x == ""))], -46)
```


```{r}
head(new_dat, 10)
```
```{r}
index <- grep("education", names(new_dat), ignore.case = TRUE)
new_dat %>% select(index)
```
```{r}
info <- subset(new_dat, subset = !is.na(NY.GDP.PCAP.CD) & !is.na(SE.SEC.CUAT.UP.FE.ZS))

info$country <- ifelse(row.names(info) != "Mexico", "Other", "Mexico")

png("Fem_High_school_GDP.png")
ggscatter(info, x = "NY.GDP.PCAP.CD", y ="SE.SEC.CUAT.UP.FE.ZS", add = "reg.line", conf.int = TRUE, cor.method = "pearson", cor.coef = TRUE, cor.coeff.args = list(label.y.npc="bottom", label.x.npc="center"), xlab = "GDP Per Capita", ylab = "Female population with at least high school at 25 years old", label = row.names(info), repel = TRUE, label.select = "Mexico", palette = "uchicago", color = "country")  #color="country", palette = c("red", "black"), fill = "lightgray")
dev.off()
```

```{r}
info <- subset(new_dat, subset = !is.na(NY.GDP.PCAP.CD) & !is.na(SL.TLF.TOTL.FE.ZS))
info$country <- ifelse(row.names(info) != "Mexico", "Other", "Mexico")

ggscatter(info, x = "NY.GDP.PCAP.CD", y ="SL.TLF.TOTL.FE.ZS", add = "reg.line", conf.int = TRUE, cor.method = "pearson", cor.coef = TRUE, cor.coeff.args = list(label.y.npc="bottom", label.x.npc="center"), xlab = "GDP Per Capita", ylab = "Percentage of female labor force", label = row.names(info), repel = TRUE, label.select = "Mexico", palette = "uchicago", color = "country")
```
```{r}

parameters <- c("SG.LEG.DVAW", "SG.LAW.EQRM.WK", "SG.LAW.NODC.HR", "SG.NOD.CONS", "SG.IND.WORK.EQ")
df <- subset(new_dat, subset = !is.na(NY.GDP.PCAP.CD) & !is.na(SG.NOD.CONS), select = c(parameters, "NY.GDP.PCAP.CD"))
df[df==0] <- "NO"
df[df==1] <- "YES"


df.m <- melt(df, id.var = "NY.GDP.PCAP.CD")

ggplot(data = df.m, aes(x=variable, y=NY.GDP.PCAP.CD)) + geom_boxplot(aes(fill=value)) + xlab("") + ylab("GDP Per Capita") + guides(fill=guide_legend(title="Has It")) + scale_x_discrete(labels=c("Legislation on\n domestic violence", "Law mandates\nequal\n remuneration","Law mandates\nnondiscrimination\nbased on gender","Nondiscrimination\nclause mentions\ngender in the\nconstitution", "Women are able\nto work in the\nsame industries\nas men"))

```
```{r}
df <- subset(new_dat, subset = !is.na(NY.GDP.PCAP.CD) & !is.na(SG.NOD.CONS), select = c(parameters, "NY.GDP.PCAP.CD"))

df <- rename(df, c("SG.LEG.DVAW"="Legislation on domestic violence",
                  "SG.LAW.EQRM.WK" ="Law mandates equal remuneration",
                  "SG.LAW.NODC.HR" = "Law mandates nondiscrimination based on gender",
                  "SG.NOD.CONS" = "Nondiscrimination clause mentions gender in the constitution",
                  "SG.IND.WORK.EQ" = "Women are able to work in the same industries as men"))

create_train_test <- function(data, size = 0.8, train = TRUE) {
    n_row = nrow(data)
    total_row = size * n_row
    train_sample <- 1: total_row
    if (train == TRUE) {
        return (data[train_sample, ])
    } else {
        return (data[-train_sample, ])
    }
}

train <- create_train_test(data = df)
test <- create_train_test(df, 0.8, train = FALSE)
#png("Laws_tree.png")
tree_model <- rpart(NY.GDP.PCAP.CD~., data = train)
rpart.plot(tree_model)
#dev.off()
```
```{r}
df <- subset(new_dat, subset = !is.na(NY.GDP.PCAP.CD) & !is.na(SG.NOD.CONS), select = c(parameters, "NY.GDP.PCAP.CD"))
model_lm <- lm(NY.GDP.PCAP.CD~., data = df)
summary(model_lm)
```