library('plm')
data('EmplUK', package = 'plm')
data('Produc', package = 'plm')
data('Grunfeld', package = 'plm')
data('Wages', package = 'plm')
head(Grunfeld)
E <- pdata.frame(EmplUK, index=c("firm","year"), drop.index=TRUE, row.names=TRUE)
head(E)
head(attr(E, "index"))
summary(E$emp)
head(as.matrix(E$emp))
head(lag(E$emp, 0:2))
head(Within(E$emp))
head(between(E$emp), 4)
head(Between(E$emp), 10)
head(as.matrix(E$emp))
head ( lag (E $ emp, 0:2 ))
head ( diff (E $ emp), 10 )
head ( lag (E $ emp, 2 ), 10 )
head ( Within (E $ emp))
head ( between (E $ emp), 4 )
head ( Between (E $ emp), 10)

grun.fe <- plm(inv~value+capital, data = Grunfeld, model = "within")
grun.re <- plm(inv~value+capital, data = Grunfeld, model = "random")
summary(grun.re)
fixef(grun.fe, type = "dmean")
summary(fixef(grun.fe, type = "dmean"))
grun.twfe <- plm(inv~value+capital, data=Grunfeld, model="within", effect="twoways") 
fixef(grun.twfe, effect="time")

grun.amem <- plm (inv ~ value + capital, data= Grunfeld, model="random", random.method="amemiya" )
ercomp (inv ~ value + capital, data= Grunfeld, method = "amemiya" , effect ="twoways" )
grun.tways <- plm(inv~value+capital, data = Grunfeld, effect = "twoways", model = "random", random.method = "amemiya")
summary(grun.tways)

data("Hedonic", package = "plm")
Hed <-plm(mv~crim+zn+indus+chas+nox+rm+age+dis+rad+tax+ptratio+blacks+lstat, data = Hedonic, model = "random", index = "townid")
summary(Hed)
punbalancedness(Hed)

znp <- pvcm(inv~value+capital, data=Grunfeld, model="within")
zplm <- plm(inv~value+capital, data=Grunfeld, model="within")
pooltest(zplm, znp)
pooltest(inv~value+capital, data=Grunfeld, model="within")
g <- plm(inv ~ value + capital, data=Grunfeld, model="pooling")
plmtest(g, effect="twoways", type="ghm")
gw <- plm(inv ~ value + capital, data=Grunfeld, effect="twoways", model="within")
gp <- plm(inv ~ value + capital, data=Grunfeld, model="pooling")
pFtest(gw, gp)

gw <- plm(inv~value+capital, data=Grunfeld, model="within")
gr <- plm(inv~value+capital, data=Grunfeld, model="random")
phtest(gw, gr)
